# docker-compose.yml
# NAPCAT_UID=$(id -u) NAPCAT_GID=$(id -g) docker-compose up -d
services:
  napcat:
    environment:
      - NAPCAT_UID=${NAPCAT_UID:-1000}
      - NAPCAT_GID=${NAPCAT_GID:-1000}
      - MODE=inkar-suki
    ports:
      - 6099:6099
    container_name: napcat
    restart: always
    image: mlikiowa/napcat-docker:latest
    volumes:
      - ./ntqq:/app/.config/QQ
    networks:
      - inkar_network
  inkar-suki:
    environment:
      - TZ=Asia/Shanghai
    image: registry.cn-hangzhou.aliyuncs.com/hzzz9/inkar-suki:latest
    container_name: inkar-suki
    restart: always
    volumes:
      - ./inkar-suki/config/config.yml:/app/src/config/config.yml
      - ./inkar-suki/data:/app/src/data
      - ./inkar-suki/const/cache:/app/src/const/cache
      - ./inkar-suki/cache:/app/src/cache
      - ./ntqq:/app/.config/QQ
    networks:
      - inkar_network
networks:
  inkar_network:
    driver: bridge
